# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-01-03 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0005_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userRank',
            field=models.IntegerField(),
        ),
    ]
